---
version: "2"
services:
  geocluster:
      image: mietzekotze/james-geocluster
      environment:
        GOOGLE_API_KEY: CULPER.GPG_KEY.wcDMAyU9PcaushSzAQv/dVyEIuQp9+jLIu1+YxrBkjUj/yOsj+3BPDDFwi7LurBUbw/VIB+2sM3uK1B5xURXhMZyyfSLIuuzeLhlblvfLpHutyG0epE3JgOIhRZUz+qdez0DEjee2vck651ciFJfZkH3nYhlC9UolO7FcdlwN1HLQtocknVhmI8HJOmfyZDqRHzv6ZtEebkxeXsYkDDk/Qi+93CO50Uw7uF2Tib8eU2/M9kxZRVNnDny/meFdQH21Iq7chE2WSvQcKr6z2sGSojPyYT1fXur6A1UzssJDai1K6RT5lertjrO2NjY/PZlYXvL+gWo1sULBx1uZV3Q91pBZ1HlYO4ZVjBx5ynKM8uXVF0nhb2YdnzxOUFvcUT51+Oqp6/Ujgkg+d+z9MRCXr46dkUCVOx7ujl5sbjpzVu2V6AraSgm4iofHvHz/x77n1G948NoR3dejk6cJhmOVvNEy923cgedoFxrCVj2tlRHeI3V3+Mrp1boFeYOhvhixfXoKLEOPeZzlqFz1flHwcFMA0vYlWdCJ7aSAQ/+I1KjLIChKcVVtGYCjlFw7bfdUC2R/0c146k/gQFXy+wTnFs4TaQSE1btXyF7s993DUKVAtGeC166P+82ANhsVwLVR8zwxMlJ7MXoCtxV0LQf8WcIOH4s++/atlvxbRuaMz4oidcPq21ieBytO/xAkTJRic74P1q9mOOS2/5DvqYt+x2N5zfXOZeJOS7MaU1UDdUIJMpedXxEocUa60GY48a80UtVxnBEYvOlME++Wum5xwQYWbFhZstuH1EgoWohqJmaELihXiXsx/xS/WnjHk0DSwMljkE8KZpcnHquvbMET9PCVVKxVgbuWjy9/aSiyt5O8UW7jnuBZVPxlQiFW2SG+mG88tOQByy71e0WsxVhS89TxBglf17vUuOgMAnrXZBX1FVuIwr75SqbI1iOeejrwBO3uVGg1s7Ig54UTHzyCllF93S6m+hvzj2XuJwEAjf/xerHEeRE1f9eFPhCS1Y41IMeSrGmLNU2fymkBw44nCU1YOlNWNnDC2iJeGVgJKHwraQeR4OJeAKg246TP8kuzaljMQVljNJMK0jngypYe0WezLVAjkUrkn7mZccwJGGQmyXECXZHO7Nrs9LVMs1U+3SrOXXKc9OfNLuwsqPdjoAjEh3AwpMTPQ/kbX+XyHeRsi9zDzxElnjQ87Hg8J64VN7honpGGYSpFkYmBwDSwgsBSoBND3zcUwoRpRTeXwNLBJ/9ds69eQDKFY81xd32IGSonHlM4824kRmOumNSVtZ6mq2XCtvBu0WfoE0vSkccuMfD0cSBo9dgUy9le4MrjpWVemyb3J1VL+rBbPO9AUki8pGRRXttrJtn8sx26lr8IuYKmmMTbGM+711BzjKAZ9sN1GexUQgy0rWtZ+wdrBFIHX7sw1e6qPaJExmkmQBSHYeoRwWhL9PDArrJTN28UNo8sXhue/klJMlmpjjKe4qnUdr1xEtEOmVW+ArGN/Hklc92PdqxpEL0ACzoZISOZRGR2Ebg2so6hQN084vsIo750lmg2Nsh1xJ6zD9D8l7o4CRj0QgV4vMtKd2d/q90L5M6jn9D2vSmb20t+qzyf0LGlv75rNgFzrsVfm1Pr0Ey/hbn/svBNxn8tv2+/nOTMu27zZJZSRiO7uhDuub3n6YUBevkPJ79V+KmU0B78ADV6PrKIpG330Mhh73/iAIAd/XRCP3qBKTYCBDlXnPgO1jtOBpHQhMFzqlQjq9SBx/leS/gzTyaTGLv+TMInteT5ZXiMRl6LceafCrUHHWWUq4GWkH3ymAc+1A0cNjSTHUE9rEVuTz4A/tcjKRfWzaXHpFsY1UwDRc0jiyxEt1ZCjV5k0UL4g/DJ4DgOWd+Lx0n7CVlLoYTwGu6LcNKQSEJz638692bNz8HYPMJXBHhveT/joK3lB121Gf4QV/mDleggU0BXeqvzpOd5RSv4TJvK0V17gXIDDfrExrD9wG30NKp2HTDp8IJGq+6GQAPk42iZZ5JnnfcbkOaMxt9KjRSsGZWHOMQWd/YEoL+Hg9FEPcvKmzYfu5Ly8cNCc5ocWTp6jKqtn88RyegntI9MP80FwqGf87eY7Z8vDhyKDIB8c2wQkZE+Qw9wxv1qMivHO+TZmQ9GwjqU8iHB9J0uJSYXfE2JCTvsdK7SotU
        RABBIT_HOST: rabbit
  postgres:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orwellcopter
    ports:
      - "5432:5432"
  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
